### ISSUE TITLE
Data Directory doesn't follow installed location

### ISSUE THREAD

**Issue by Gleekop** [timmo001/home-assistant-assist-desktop#33]
I installed this software using an administrator account, but I can't run it using my normal user account. I get the following error:

![Assist on PC Error](https://github.com/timmo001/home-assistant-assist-desktop/assets/62856920/ed31af28-57e3-409e-bc0e-8d5b3622cb84)

During the installation, I changed the folder where the software was to be installed, putting it in "C:\Users\Program Files\Home Assistant Assist". The data directory seems to be hard-coded.

I also didn't get the "Home Assistant" folder created on my normal account Start Button.

**Comment by timmo001** [comment]
I'm not sure what this might be, as I have used the default tauri app data directory

https://github.com/timmo001/home-assistant-assist-desktop/blob/f08eb272da625f2d2d5051bce3e7b75469afd341/src-tauri/src/main.rs#L81-L89

I don't think having a user directory named "Progam Files" is very standard for windows however
